### PR TITLE
Use class field syntax to bind clicked method

### PR DESCRIPTION
**Pull request by julien-f**
Because you may as well go all the way and ditch the constructor :)

### CODE REVIEW

**Comment by littledan** [comment]
That actually doesn't work :( . This is due to our decision to use "Define" semantics rather than "Set" semantics.

**Comment by julien-f** [comment]
I understand it's different, but why doesn't it work?

**Comment by littledan** [comment]
It doesn't work because the DOM's onclick setter would not be called--you'd have an own property called onclick, and it wouldn't be triggered when a user clicks on the element.

**Comment by julien-f** [comment]
Unnderstood, I did not see it was triggering a setter.

Sorry for the noise 😄

**Pull request closed without merging**
