### PR TITLE
Add link to SpiderMonkey bug

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by littledan** [comment]
s/Planned/In progress/  :)

**Comment by littledan** [comment]
There's actually another link that shows the progress...

**Comment by littledan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1499448

**Comment by chicoxyzzy** [comment]
updated

**Comment by littledan** [comment]
Perfect, thanks!

**Comment by littledan** [comment]
Perfect, thanks!

**Pull request merged**
